### ISSUE TITLE
Dates incorrectly marked as not trading days

### ISSUE THREAD

**Issue by hhultin** [SwedishHouseofFinance/SHoF-Platform-Issue-Tracker#3]
I am trying to use the Nasdaq database with the order book view query. For some dates it works, but for quite many dates I get the pop-up "WARNING The selected day was not a trading day", even though those dates should be trading days. 

Example of dates not working:
2019-10-28
2019-10-29
2020-02-04
2020-03-04
2020-04-02
2020-05-08

**Comment by CarminePalombo** [comment]
Some days are missing from the timeseries because the files we receive from NASDAQ for those days are corrupt.
We are working with NASDAQ in order to re-recreate those files.
Meanwhile we are filling the gaps with the valid data we are able to extract from the corrupt files.
It will be a long process, in the future refer to https://support.data.houseoffinance.se/ for updates.
