### ISSUE TITLE
Bug: Nasdaq HFT - Missing dates for "Reconstructed Order Book"

### ISSUE THREAD

**Issue by ljaacc** [SwedishHouseofFinance/SHoF-Platform-Issue-Tracker#7]
Hi,

I am trying to request a dataset from Nasdaq HFT with time range 2020-04-01 - 2020-09-30 for Swedish stocks listed on the Stockholm Stock Exchange. However, there are several days missing data each month for every dataset that I am trying to generate. An example, for SE0007100581 over the period (aggregated values with a frequency every millisecond) there is only data generated for 10 trading days out of 19 in April and only 6 days of data generated for August and 4 days generated in September. 

Could you please check and advise?

**Comment by CarminePalombo** [comment]
Some days are missing from the timeseries because the files we receive from NASDAQ for those days are corrupt.
We are working with NASDAQ in order to re-recreate those files.
Meanwhile we are filling the gaps with the valid data we are able to extract from the corrupt files.
It will be a long process, in the future refer to https://support.data.houseoffinance.se/ for updates.
